spring:
  datasource:
    url: jdbc:postgresql://bookshop-postgres/bookshopdb_file
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://bookshop-keycloak/realms/PolarBookshop

file:
  upload-dir: /home/uploads