spring:
  r2dbc:
    url: r2dbc:postgresql://bookshop-postgres/bookshopdb_file
  flyway:
    url: jdbc:postgresql://bookshop-postgres/bookshopdb_file
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://bookshop-keycloak/realms/PolarBookshop

file:
  upload-dir: /app/uploads
