apiVersion: v1
kind: Service
metadata:
  name: file-service
  labels:
    app: file-service

spec:
  type: ClusterIP
  selector:
    app: file-service
  ports:
    - protocol: TCP
      port: 9008
      targetPort: 9008